/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["healthCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/characters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get available characters */
        get: operations["getCharacters"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all runs with optional filtering */
        get: operations["getRuns"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{character}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get runs for a specific character */
        get: operations["getCharacterRuns"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get aggregated stats for all characters */
        get: operations["getStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats/{character}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get stats for a specific character */
        get: operations["getCharacterStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get complete export data */
        get: operations["getExport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            /** @enum {string} */
            status: "healthy" | "unhealthy";
            /** Format: date-time */
            timestamp: string;
            version?: string;
        };
        Character: {
            /** @description Character identifier (e.g., IRONCLAD) */
            id: string;
            /** @description Display name (e.g., Ironclad) */
            name: string;
        };
        RunMetrics: {
            play_id: string;
            character: string;
            floor_reached: number;
            victory: boolean;
            score: number;
            ascension_level?: number;
            deck_size?: number;
            attack_count?: number;
            skill_count?: number;
            power_count?: number;
            upgraded_cards?: number;
            cards_removed?: number;
            relic_count?: number;
            /** @description List of relic names obtained during the run */
            relics?: string[];
            /** @description List of card names in the final deck */
            master_deck?: string[];
            elites_killed?: number;
            bosses_killed?: number;
            campfires_rested?: number;
            campfires_upgraded?: number;
            shops_visited?: number;
            cards_purchased?: number;
            potions_used?: number;
            total_damage_taken?: number;
            max_hp_at_end?: number;
            killed_by?: string | null;
        };
        CharacterStats: {
            character: string;
            display_name: string;
            total_runs: number;
            wins: number;
            /** Format: double */
            win_rate: number;
            /** Format: double */
            avg_score?: number;
            /** Format: double */
            avg_floor?: number;
            max_floor?: number;
            /** Format: double */
            avg_deck_size?: number;
            /** Format: double */
            avg_relics?: number;
        };
        ExportData: {
            runs: components["schemas"]["RunMetrics"][];
            character_stats: components["schemas"]["CharacterStats"][];
            /** Format: int64 */
            export_timestamp: number;
        };
        ApiError: {
            error: string;
            code: string;
            details?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description API is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    getCharacters: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of characters */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Character"][];
                };
            };
        };
    };
    getRuns: {
        parameters: {
            query?: {
                /** @description Filter by character name */
                character?: string;
                /** @description Only return victories */
                victories_only?: boolean;
                /** @description Minimum ascension level */
                min_ascension?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of runs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunMetrics"][];
                };
            };
        };
    };
    getCharacterRuns: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Character name (IRONCLAD, THE_SILENT, DEFECT, WATCHER) */
                character: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Character runs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunMetrics"][];
                };
            };
            /** @description Character not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    getStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Character statistics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CharacterStats"][];
                };
            };
        };
    };
    getCharacterStats: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                character: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Character statistics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CharacterStats"];
                };
            };
            /** @description Character not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    getExport: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Complete export data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportData"];
                };
            };
        };
    };
}
